# Generated by Django 4.1 on 2023-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
