# Generated by Django 4.1 on 2023-02-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
    ]
