# Generated by Django 4.1 on 2023-02-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
