# Generated by Django 4.1 on 2023-02-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
