# Generated by Django 4.1 on 2023-02-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
